<a href="https://colab.research.google.com/github/anushi1983/dedicated_ds/blob/main/GradientDescentNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib as plt
%matplotlib inline

In [2]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/My Drive/insurance.csv')

Mounted at /content/drive


In [3]:
df.head()

age  affordability  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
df.shape

(27, 3)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df[['age','affordability']],df['bought_insurance'],test_size=0.2,random_state=23)

In [6]:
len(X_train)

21

In [7]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100
X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [8]:
X_train_scaled

age  affordability
14  0.49              1
23  0.45              1
10  0.18              1
0   0.22              1
15  0.55              1
5   0.56              1
11  0.28              1
2   0.47              1
1   0.25              0
26  0.23              1
20  0.21              1
25  0.54              1
7   0.60              0
12  0.27              0
13  0.29              0
24  0.50              1
22  0.40              1
9   0.61              1
8   0.62              1
6   0.55              0
19  0.18              1

In [9]:
model=keras.Sequential([
  keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

In [10]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(X_train_scaled,y_train,epochs=5000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 6ms/step - loss: 0.4632 - accuracy: 0.9048
Epoch 2502/5000
1/1 [==============================] - 0s 8ms/step - loss: 0.4631 - accuracy: 0.9048
Epoch 2503/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.4630 - accuracy: 0.9048
Epoch 2504/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.4630 - accuracy: 0.9048
Epoch 2505/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.4629 - accuracy: 0.9048
Epoch 2506/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.4629 - accuracy: 0.9048
Epoch 2507/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.4628 - accuracy: 0.9048
Epoch 2508/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.4627 - accuracy: 0.9048
Epoch 2509/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.4627 - accuracy: 0.9048
Epoch 2510/5000
1/1 [==============================] -

In [11]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 240ms/step - loss: 0.5583 - accuracy: 0.8333


[0.5583400130271912, 0.8333333134651184]

In [12]:
model.predict(X_test_scaled)

array([[0.09614235],
       [0.13812745],
       [0.7133522 ],
       [0.4235038 ],
       [0.8340248 ],
       [0.13130268]], dtype=float32)

In [13]:
X_test_scaled

age  affordability
18  0.19              0
21  0.26              0
4   0.46              1
3   0.52              0
17  0.58              1
16  0.25              0

In [14]:
coef,intercept=model.get_weights()

In [15]:
coef,intercept

(array([[5.8558636],
        [1.5714792]], dtype=float32), array([-3.3534553], dtype=float32))

In [24]:
import math
def sigmoid(x):
  z=1/(1+math.exp(-x))
 
  return z
sigmoid(18)

0.9999999847700205

In [25]:
def predict(age,aff):
  weighted_sum=coef[0]*age+coef[1]*aff+intercept
  return sigmoid(weighted_sum)

In [27]:
predict (0.46,1)

0.7133522016355615

In [45]:
def log_loss(yt,yp):
  eps=1e-15
  yp_new=[max(i,eps) for i in yp]
  yp_new=[min(i,1-eps) for i in yp_new]
  yp_new= np.array(yp_new)
  prec=-np.mean(yt*np.log(yp_new)+(1-yt)*np.log(1-yp_new))
  return prec

In [30]:
def sigmoid_np(x):
  return 1/(1+np.exp(-x))
sigmoid_np(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [78]:
class MyNN:
  def _init_(self):
    self.w1=1
    self.w2=1
    self.bias=0
  def fit(self,X,y,epochs,loss_threshold= 0.3426):
    self.w1,self.w2,self.bias=self.gradient_descent(X['age'],X['affordability'],y,epochs,loss_threshold)
  def predict(self,X):
    weighted_sum=self.w1*X['age']+self.w2*X['affordability']+self.bias
    predicted= self.sigmoid_np(weighted_sum)
    return(predicted)
  def sigmoid_np(self,x):
    return 1/(1+np.exp(-x)) 
  def gradient_descent(self,age,aff,yt,epochs,loss_threshold):
    #weighted sum and bias
    w1=w2=1
    bias=0.1
    rate=0.5
    n=len(age)
    for i in range(epochs):
      weighted_sum=w1*age+w2*aff+bias
      y= self.sigmoid_np(weighted_sum)
      dw=(1/n)*np.dot(np.transpose(age),(y-yt))
      db=(1/n)*np.dot(np.transpose(aff),(y-yt))
      bias_d=np.mean(y-yt)
      loss=log_loss(yt,y)
      w1=w1-(rate *dw)
      w2=w2-(rate *db)
      bias=bias-rate*bias_d
      if i%10==0:
        print(f'Epoch={i}, w1={w1}, w2:{w2}, bias:{bias},  loss:{loss}')
      if loss < loss_threshold :
        break
    return w1,w2,bias


In [51]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordability'],y_train,1000)

Epoch=0, w1=0.980601385963073, w2:0.9267628222320171, bias:-0.023226641851043936,  loss:0.7283126309971776
Epoch=1, w1=0.9674913974521645, w2:0.8658418368954529, bias:-0.1304366941694034,  loss:0.6894071483304105
Epoch=2, w1=0.9602454699375564, w2:0.8165617743866632, bias:-0.22275697024715674,  loss:0.6610027268516663
Epoch=3, w1=0.9582509875385333, w2:0.7778004707245775, bias:-0.3017700222112327,  loss:0.6407616136714289
Epoch=4, w1=0.9608055054228933, w2:0.7482014120136689, bias:-0.3692661971845413,  loss:0.6265275636945742
Epoch=5, w1=0.967198722795683, w2:0.7263563424873378, bias:-0.4270405847876242,  loss:0.6165221566019036
Epoch=6, w1=0.9767671536931307, w2:0.7109301613009339, bias:-0.47676009992947554,  loss:0.6093933608380893
Epoch=7, w1=0.9889229189914426, w2:0.7007293139684841, bias:-0.5198953649202526,  loss:0.6041724785740669
Epoch=8, w1=1.003163549679837, w2:0.6947280023755572, bias:-0.5576993179725885,  loss:0.6001945536534772
Epoch=9, w1=1.019070125228562, w2:0.692068062

(5.8348399137247915, 1.6381387717285338, -3.426068472044945)

In [52]:
coef,intercept

(array([[5.8558636],
        [1.5714792]], dtype=float32), array([-3.3534553], dtype=float32))

In [82]:
custom_model=MyNN()
custom_model.fit(X_train_scaled,y_train,300)


Epoch=0, w1=0.980601385963073, w2:0.9267628222320171, bias:-0.023226641851043936,  loss:0.7283126309971776
Epoch=10, w1=1.0362993857026086, w2:0.6920448965828717, bias:-0.6212919064382747,  loss:0.5943513493757002
Epoch=20, w1=1.2408083412047162, w2:0.7536246564462976, bias:-0.8334602928303759,  loss:0.5754235004304873
Epoch=30, w1=1.4583846252721218, w2:0.8351212153227291, bias:-0.9972723925839172,  loss:0.5591591848686972
Epoch=40, w1=1.674813916910754, w2:0.9094689721888104, bias:-1.1482727465104028,  loss:0.5440438355104471
Epoch=50, w1=1.8885839020893762, w2:0.9756096627664663, bias:-1.290636537766278,  loss:0.5299058574596641
Epoch=60, w1=2.099363875579489, w2:1.0345887150686182, bias:-1.425610515015073,  loss:0.5166196080811593
Epoch=70, w1=2.3069762586826776, w2:1.0874629493356716, bias:-1.5540529593148735,  loss:0.5040860115545118
Epoch=80, w1=2.5112970668714523, w2:1.1351408019901046, bias:-1.6766797159583184,  loss:0.49222569684567724
Epoch=90, w1=2.712240146699697, w2:1.178

In [83]:
custom_model.predict(X_test_scaled)

18    0.089688
21    0.129092
4     0.710147
3     0.403248
17    0.831497
16    0.122673
dtype: float64

In [84]:
model.predict(X_test_scaled)

array([[0.09614235],
       [0.13812745],
       [0.7133522 ],
       [0.4235038 ],
       [0.8340248 ],
       [0.13130268]], dtype=float32)

In [81]:
y_test

18    0
21    0
4     1
3     0
17    1
16    1
Name: bought_insurance, dtype: int64